services:
    video_cut.command:
        class: MyskillsBundle\Command\VideoCutCommand
        arguments:
        - "@video.manager"
        - "@video_clip.manager"
        - "%web_directory%"
        - "@video"
        - "@doctrine.orm.entity_manager"
        tags:
        -  { name: console.command }

    e_books_parser.command:
        class: MyskillsBundle\Command\EnglishEReaderNetParserCommand
        arguments:
        - "@doctrine.orm.entity_manager"
        - "@book.manager"
        - "%web_directory%"
        tags:
        -  { name: console.command }
        calls:
        - [setUser, ["%proxy_user%"]]
        - [setPass, ["%proxy_pass%"]]

    youtube_parser.command:
        class: MyskillsBundle\Command\YoutubeParserCommand
        arguments:
        - "@video.manager"
        - "@doctrine.orm.entity_manager"
        - "%web_directory%"
        tags:
        -  { name: console.command }