services:
    dict_source.repository:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
        - MyskillsBundle\Entity\DictSource

    dict_translation_en_ru.repository:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
        - MyskillsBundle\Entity\DictTranslationEnRu

    dict_translation_ru_en.repository:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
        - MyskillsBundle\Entity\DictTranslationRuEn

    dict_word_en.repository:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
        - MyskillsBundle\Entity\DictWordEn

    dict_word_ru.repository:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
        - MyskillsBundle\Entity\DictWordRu

    genre.repository:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
        - MyskillsBundle\Entity\Genre

    tag.repository:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
        - MyskillsBundle\Entity\Tag

    video_clip.repository:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
        - MyskillsBundle\Entity\VideoClip

    video_file.repository:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
        - MyskillsBundle\Entity\VideoFile

    vtt_subtitle.repository:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
        - MyskillsBundle\Entity\VttSubtitle

    video.repository:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
        - MyskillsBundle\Entity\Video

    user_word.repository:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
        - MyskillsBundle\Entity\UserWord

    user_folder.repository:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
        - MyskillsBundle\Entity\UserFolder

    game.repository:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
        - MyskillsBundle\Entity\Game

    book.repository:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
        - MyskillsBundle\Entity\Book