services:
    base.controller:
        abstract: true
        calls:
        - [setLogger, ["@logger"]]
        - [setCacheService, ["@memcached_cache"]]
        - [setSerializer, ["@app_serializer"]]
        - [setRequestStack, ["@request_stack"]]
        - [setTemplating, ["@templating"]]
        - [setRouter, ["@router"]]
        - [setTokenStorage, ["@security.token_storage"]]
        - [setFormFactory, ["@form.factory"]]
        - [setTokenizer, ["@tokenizer"]]

    main.controller:
        parent: base.controller
        class: MyskillsBundle\Controller\MainController

    book.controller:
        parent: base.controller
        class: MyskillsBundle\Controller\BookController
        arguments:
        - "@book.manager"

    dictionary.controller:
        parent: base.controller
        class: MyskillsBundle\Controller\DictionaryController
        arguments:
        - "@dictionary_en_ru.manager"
        - "@dictionary_ru_en.manager"
        - "@search.controller"

    search.controller:
        parent: base.controller
        class: MyskillsBundle\Controller\SearchController
        arguments:
        - "@search.manager"

    api_translation.controller:
        parent: base.controller
        class: MyskillsBundle\Controller\ApiTranslationController
        arguments:
        - "@api_translation.manager"

    user_dictionary.controller:
        parent: base.controller
        class: MyskillsBundle\Controller\UserDictionaryController
        arguments:
        - "@user_dictionary.manager"

    user.controller:
        parent: base.controller
        class: MyskillsBundle\Controller\UserController
        arguments:
        - "@user.manager"

    game.controller:
        parent: base.controller
        class: MyskillsBundle\Controller\GameController
        arguments:
        - "@game.manager"
        - "@user.manager"

    error.controller:
        parent: base.controller
        class: MyskillsBundle\Controller\ErrorController