sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.admin.block.search_result:
            contexts: [admin]
        sonata.admin.block.admin_list:
            contexts: [admin]

        #sonata.admin_doctrine_orm.block.audit:
        #    contexts:   [admin]

        sonata.block.service.text:
        sonata.block.service.rss:
        sonata.user.block.menu:    # used to display the menu in profile pages
        sonata.user.block.account:

sonata_admin:
    title: Admin section
    dashboard:
        blocks:
            # display a dashboard block
            - { position: left, type: sonata.admin.block.admin_list }
            - { position: right, type: sonata.block.service.text, settings: { content: ""} }
    security:
        handler: sonata.admin.security.handler.acl
        # acl security information
        information:
            GUEST:    [VIEW, LIST]
            STAFF:    [EDIT, LIST, CREATE]
            EDITOR:   [OPERATOR, EXPORT]
            ADMIN:    [MASTER]
        # permissions not related to an object instance and also to be available when objects do not exist
        # the DELETE admin permission means the user is allowed to batch delete objects
        admin_permissions: [CREATE, LIST, DELETE, UNDELETE, EXPORT, OPERATOR, MASTER]
        # permission related to the objects
        object_permissions: [VIEW, EDIT, DELETE, UNDELETE, OPERATOR, MASTER, OWNER]
    templates:
        layout:  SonataAdminBundle::layout.html.twig

sonata_user:
    security_acl: false
    class:
        user:         Application\Sonata\UserBundle\Entity\User
        group:        Application\Sonata\UserBundle\Entity\Group
    profile:  # Profile Form (firstname, lastname, etc ...)
        register:
            form:
                type:           video_user_registration
                handler:        sonata.user.registration.form.handler.default
                name:           video_user_registration_form
        form:
            type:               video_user_profile
            handler:            sonata.user.profile.form.handler.default
            name:               video_user_profile_form
            validation_groups:  [Profile]
    manager_type: orm

sonata_doctrine_orm_admin:
    templates:
        form:
            - MyskillsBundle:Admin:my_form_admin_fields.html.twig
